### ISSUE TITLE
Model Malia.pof causes pof-tools crash

### ISSUE THREAD

**Issue by tomimaki** [Baezon/pof-tools#123]
This model
[Malia.zip](https://github.com/Baezon/pof-tools/files/10716064/Malia.zip)
causes crash. PCS2 can open it. Vishnan Arbiter from Blue Planet is the same model and crashes too.
Error info:
called` `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [67, 111, 98, 50, 102, 115, 32, 86, 101, 114, 115, 105, 111, 110, 32, 48, 46, 48, 53, 32, 57, 45, 52, 45, 57, 57, 10, 195, 83, 255, 131, 195, 161, 180, 224, 66, 229, 201, 88, 66, 49], error: Utf8Error { valid_up_to: 27, error_len: Some(1) } },  C:\Users\Marcus\pof-tools\pof\src\parse.rs:418:77

**Comment by digama0** [comment]
This is bad UTF-8 in the info section. It apparently says:
```

**Comment by tomimaki** [comment]
Interesting. Deleted malformed thing and I could open model in poof-tools.

**Comment by qazwsxal** [comment]
This has been fixed in #120 , next release should open it without trouble (but will drop the corrupted info)

**Comment by tomimaki** [comment]
Ah, I didn't check current source. Closing because it's fixed.
