### ISSUE TITLE
Virus detected in download

### ISSUE THREAD

**Issue by lordwahu** [Baezon/pof-tools#159]
Attempting to download the pof-tool-for-windows.zip was blocked with the warning that "Trojan: Script/Wacatac.B!ml was detected" preventing me from downloading the tool

**Comment by digama0** [comment]
What antivirus triggered this? There is certainly no virus in the release, but if you would like to be sure you can always build it from source - you will need to [install rust](https://rustup.rs) and then use `cargo build --release` to produce the executable. You can presumably also disable your antivirus while downloading it.

**Comment by Baezon** [comment]
The vigilance is appreciated, going to close the 'pof tools is actually a virus' book for now though.
