### ISSUE TITLE
FR: Draw sticks for lollipops over model

### ISSUE THREAD

**Issue by EatThePath** [Baezon/pof-tools#22]
Sticks are obscured by model geo, which is unhelpful in some cases

**Comment by Baezon** [comment]
I had considered this, but I did this on purpose to better indicate the actual position of a lollipop relative to the model. If too much is not occluded by the model it becomes difficult to spatially understand where it lies relative to the model without having to look at it from a bunch of angles.

**Comment by EatThePath** [comment]
possibly. My immediate use case is setting up glowpoints that are actually inside the model for light casting

**Comment by Baezon** [comment]
Use wireframe mode?

**Comment by EatThePath** [comment]
That'd work! Before you mentioned it I didn't realize the wireframe mode button was that, to me it communicates more 'frame ship in camera' as the function I expected from it

**Comment by Baezon** [comment]
Yes, those buttons need some work, probably going to do custom sprites.
