### ISSUE TITLE
Improve BSP data flexibility and compactness

### ISSUE THREAD

**Issue by Baezon** [Baezon/pof-tools#36]
Will require a version bump of course, but several things that come to mind are:

1. Removing various vestigal bits of data from existing chunks, as a *significant* amount of disk space can be taken up by them
2. Add support for more than 65k verts/norms. This will noticeably increase filesizes, but the above should be able to even it out.
3. Express/re-arrange the same data using completely new chunk types? There are several invariants to the system which better organized chunks could take advantage of and further decrease filesizes.

**Comment by Baezon** [comment]
Ok, here's my idea for the new setup. Firstly, here's a basic diagram of how the chunks are sort of laid out (the red Xs and green arrows are proposed changes):

![Untitled](https://user-images.githubusercontent.com/17305613/163871888-be43b2a5-f789-41c3-95de-fa997096f7e3.png)

The changes are threefold:
- A lot less EOF chunks. The spec allows for multiple SORTNORMs punctuated by an EOF, but the engine explicitly rejects multiple and asserts that each one is immediately followed by an EOF, therefore, with a SORTNORM2, an EOF can be merely *assumed*, and we can save the bytes spent on explicitly writing an EOF. 
- Similarly, the spec allows for multiple TMAPPOLYs before being punctuated by an EOF, and this is even used by some retail model. However in a BSP Tree multiple polies on a leaf are merely watering down our efficiency, and it's not hard to split them up by more SORTNORMs. So, again, a TMAP2POLY should only contain one polygon, and be *assumed* to end there, without an EOF.
-  Since there is now one polygon per leaf, and there must always be a BOUNDBOX per leaf, these two chunks can be merged together, so the TMAP2POLY would also contain bounding box info, saving the space of yet another separate chunk.


With this, and a host of removed vestigal fields the spec becomes this:
```
SORTNORM2
+ 0 int id = 7
+ 4 int size
+ 8 int front_offset // Only recurse into this if non-zero.
+ 12 int back_offset // Only recurse into this if non-zero.
+ 16 vector min_bounding_box_point 
+ 28 vector max_bounding_box_point
```


```
TMAP2POLY 
+ 0 int id = 6
+ 4 int size
+ 8 vector min_bounding_box_point 
+ 20 vector max_bounding_box_point 
+ 32 vector normal
+ 44 int nverts
+ 48 int tmap_num
for each vertex, i {
 uint vertnum[i]
 uint normnum[i]
 float u[i]
 float v[i]
}
```

Based on back of the napkin calculations and early testing all this results in file size savings of up to 25%!

**Comment by digama0** [comment]
Flipping the order of `nverts` and `tmap_num` would simplify the parsing, at least in pof-tools, since it prefers that the count field immediately precedes the list of things.

**Comment by Baezon** [comment]
I would prefer the simplicity of the API to have less chunks, given the somewhat marginal degree of space savings in that case. Agreed on the `nverts` and `tmap_num` though
