### ISSUE TITLE
Bug: setting a rotation axis

### ISSUE THREAD

**Issue by Goober5000** [Baezon/pof-tools#64]
I loaded up a model that had no rotation axis on a certain subobject.  Using POF Tools, I set the rotation axis to the Z-axis and saved it.  However, the model does not rotate in game.  Furthermore, loading the model in PCS2 still shows no rotation axis, even though loading the model in POF Tools shows the Z-axis.

**Comment by Baezon** [comment]
Can you attach the .pof?

**Comment by digama0** [comment]
I suspect the issue is that there is no UI for setting the `movement_type`, so even if you set the `movement_axis` to Z the `movement_type` will remain at `None` and hence it won't rotate. I think PCS2 also checks the movement type to decide whether to show the movement axis.

**Comment by Goober5000** [comment]
Sounds plausible.  Here is the model, which shows the axis in POF Tools but not PCS2.
[MarnakhKnossos.zip](https://github.com/Baezon/pof-tools/files/8517539/MarnakhKnossos.zip)

**Comment by digama0** [comment]
[PCS2 does indeed clear the movement axis if the movement type is `None`.](https://github.com/scp-fs2open/PCS2/blob/066811eec335a12777280e8d3b3f69403ff678ea/src/SOBJ_editor.h#L103-L105)
