### ISSUE TITLE
Orthographic View and "View From" options.

### ISSUE THREAD

**Issue by JadedDragoon** [Baezon/pof-tools#70]
Might need to separate as two feature requests but they both are for the same use-case.

When making radar icons I would load the model in pcs2, switch to orthographic view, and then use the buttons to view the model from exactly above, or exactly the right side, etc. Screenshot and I now have a base shape for the icon I can do whatever with in Photoshop.

I figure this is outside the intended use of Pof Tools and I can keep using pcs2 for this if need be, but it would be awful nice if you could add these.

**Comment by Baezon** [comment]
Yes, they're good ideas and definitely planned

**Comment by Baezon** [comment]
Implemented in #100
