### ISSUE TITLE
gltf Bug?

### ISSUE THREAD

**Issue by wookieejedi** [Baezon/pof-tools#85]
Have a rather large model with lots of turrets, paths, etc. I saved it as gltf then try to import into blender though I get this message `Couldn't parse glTG. Check that the file is valid.`
[liberty.zip](https://github.com/Baezon/pof-tools/files/9227563/liberty.zip)

**Comment by digama0** [comment]
I was able to confirm the issue.

**Comment by digama0** [comment]
The problem is that the model contains some path points that are at NaN positions (`$path69` - `$path85` are all NaN). Asteroth is on vacation but I'll ask him what he wants to do about this when he returns. For now I'll just set them all to 0 during export to prevent export failures.
